### ISSUE TITLE
SH1106 OLED blank

### ISSUE THREAD

**Issue by Marcusv2** [piotrwawrzyn/simple-arduino-crypto-display#4]
Seems I cant get the SH1106 to display anything.

It is a generic screen with 0x78 and 0x7A addresses, I have tried swapping the address with no luck.

Where is it finding "SH1106.h"? Perhaps I am missing that?

**Comment by MrPepino** [comment]
Should be this one in the library manager:
![image](https://user-images.githubusercontent.com/6870531/115990907-22bf4480-a5c6-11eb-9cc5-87d37b48da5a.png)

However I'm using an exact copy of the libraries used by the maintainer of this fork because of several issues with my SH1106. If the one above doesn't work, try the 4.1.0 we use from https://www.arduinolibraries.info/libraries/esp8266-and-esp32-oled-driver-for-ssd1306-displays.

**Comment by Marcusv2** [comment]
Thanks mate. I ended up just going with a SSD1306.
